export const strings = {
  login: {
    mobile: "Mobile Number",
    password: "Password",
    changeText: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    loginText: "Login",
    forgotPassword: "Forgot Password?",
    logoutConfirmation: "Are you sure you want to logout?",
    changePasswordSuccess: "Password changed successfully, please relogin",
    mobileRequired: "Mobile number is required",
    passwordRequired: "Password is required",
    invalidMobile: "Please enter a valid mobile number",
    enterPassword: "Please enter password",
    passwordResetSuccess: "Password reset successfully, please check your mail",
  },
  alert: {
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Info",
    ok: "OK",
    cancel: "Cancel",
  },
  homeMenu: {
    showQr: "Show QR",
    applyLeave: "Apply Leave",
    viewBill: "View Bill",
    leaveHistory: "Leave History",
    scanQr: "Scan QR",
    todayLeaves: `Today's Leaves`,
    submitAttendance: "Submit Final attendance",
    collection: "Monthly Collection",
  },
  headers: {
    home: "Home",
    changePassword: "Change Password",
    billingHistory: "Billing History",
    logout: "Logout",
    scanQr: "Scan QR",
    showQr: "Show QR",
    applyLeave: "Apply Leave",
    leaveHistory: "Leave History",
    leaveDetails: "Leave Deatils",
    viewBill: "View Bill",
  },
  leave: {
    toDate: "To Date",
    fromDate: "From Date",
    applyLeaveSuccess: "Leaves submited successfulluy",
    cancelled:'Cancelled',
    active:'Active',
    date: "Date:",
  },
  bill: {
    transId: "Transaction ID",
  },
  common: {
    submit: "Submit",
    viewBillDisableText: "View bill enabled every month 1 to 5",
  },
  qr: {
    processing: "Processing...",
    scanPrompt: "Scan QR code to mark attendance",
    invalidFormat: "Invalid QR code format",
    saved: "Meal entry saved!",
    duplicate: "Duplicate entry: This meal has already been recorded.",
    failed: "Failed to save meal entry",
    grantPermission: "Grant permission",
    needPermission: "We need your permission to show the camera",
  },
  bills: {
    hi: "Hi",
    transactionId: "Transaction ID",
    noHistory: "No billing history available.",
    daysPresent: "Days Present",
    daysAbsent: "Days Absent",
    transactionImage: "Transaction Image",
    uploadImage: "Upload Image",
  },
  leaves: {
    noLeaves: "No leaves available.",
    chosenDays: (days: string) => `You have chosen ${days} days leaves`,
  },
  errors: {
    passwordsDoNotMatch: "Passwords do not match",
    passwordCriteria: "Password does not meet the criteria",
    failedInitDB: "Failed to initialize local DB",
  },
};
