import { forgotPassword } from "../store/reducers/authSlice";

export const strings = {
  login: {
    mobile: "Mobile Number",
    password: "Password",
    changeText: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    loginText: "Login",
    forgotPassword: "Forgot Password?",
    forgotPasswordText: "Forgot Password",
    logoutConfirmation: "Are you sure you want to logout?",
    changePasswordSuccess: "Password changed successfully, please relogin",
    mobileRequired: "Mobile number is required",
    passwordRequired: "Password is required",
    invalidMobile: "Please enter a valid mobile number",
    enterPassword: "Please enter password",
    passwordResetSuccess: "Password reset successfully, please check your mail",
    passwordMinLength: "Password must be at least 8 characters",
    passwordRegexError:
      "Password must contain uppercase, lowercase, number, and special character",
    passwordsDoNotMatch: "Passwords do not match",
    firstTimeChangePasswordMsg:
      "Please change your default password to continue further",
    rememberMe: "Remember me",
    checkboxChecked: "☑",
    checkboxUnchecked: "☐",
  },
  alert: {
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Info",
    ok: "OK",
    cancel: "Cancel",
    confirm: "Confirm",
  },
  homeMenu: {
    showQr: "Show QR",
    applyLeave: "Apply Leave",
    viewBill: "View Bill",
    leaveHistory: "Leave History",
    scanQr: "Scan QR",
    todayLeaves: `Today's Leaves`,
    submitAttendance: "Submit Final attendance",
    collection: "Monthly Collection",
  },
  headers: {
    home: "Home",
    changePassword: "Change Password",
    billingHistory: "Billing History",
    contactUs: "Contact Us",
    yourMenu: "Your menu",
    logout: "Logout",
    scanQr: "Scan QR",
    showQr: "Show QR",
    applyLeave: "Apply Leave",
    leaveHistory: "Leave History",
    leaveDetails: "Leave Deatils",
    viewBill: "View Bill",
    attendanceSubmission: "Submit Attendance",
  },
  leave: {
    toDate: "To Date",
    fromDate: "From Date",
    applyLeaveSuccess: "Leaves submited successfulluy",
    cancelled: "Cancelled",
    active: "Active",
    date: "Date:",
  },
  bill: {
    transId: "Transaction ID",
  },
  common: {
    submit: "Submit",
    viewBillDisableText: "View bill enabled every month 1 to 5",
  },
  qr: {
    processing: "Processing...",
    scanPrompt: "Scan QR code to mark attendance",
    invalidFormat: "Invalid QR code format",
    saved: "Meal entry saved!",
    duplicate: "Duplicate entry: This meal has already been recorded.",
    failed: "Failed to save meal entry",
    grantPermission: "Grant permission",
    needPermission: "We need your permission to show the camera",
  },
  attendance: {
    totalMealEntries: "Total meal entries:",
    mealIds: "Meal IDs:",
    markAttendance: "Mark Attendance",
    noEntries: "There are no meal entries to submit.",
    noEntriesFound: "No entries found",
    submitted: "Attendance submitted",
    failedSubmit: "Failed to submit attendance",
    confirmSubmit: (count: number) => `Submit ${count} attendance entries?`,
  },
  bills: {
    hi: "Hi",
    transactionId: "Transaction ID",
    upiApps: " UPI Apps",
    noHistory: "No billing history available.",
    daysPresent: "Days Present",
    daysAbsent: "Days Absent",
    transactionImage: "Transaction Image",
    uploadImage: "Upload Transaction Image",
    billAmount: "Bill Amount",
    transactionIdRequired: "Transaction ID is required.",
    billAmountTooltip: "This bill amount calculated like Day Present* 160",
  },
  leaves: {
    noLeaves: "No leaves available.",
    chosenDays: (days: string) => `You have chosen ${days} days leaves`,
  },
  errors: {
    passwordsDoNotMatch: "Passwords do not match",
    passwordCriteria: "Password does not meet the criteria",
    failedInitDB: "Failed to initialize local DB",
  },
  menu: {
    day: "Day",
    mealType: "Meal Type",
    foodItems: "Food Items",
    foodItemName: "Food Item Name",
    foodItemNameRequired: "Please enter food item name.",
    noMenu: "No menu available.",
    startTime: "Start Time",
    endTime: "End Time",
    meals: "Meals",
    addMeal: "Add Meal",
    mealName: "Meal Name",
    mealNameRequired: "Please enter meal name.",
    startTimeRequired: "Please select start time.",
    endTimeRequired: "Please select end time.",
    addFoodItem: "Add Food Item",
    close: "Close",
    editMeal: "Edit Meal",
    deleteMealConfirmation: "Are you sure you want to delete this meal?",
  },
};
